//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPCookBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientesReceita
    {
        public int ID { get; set; }
        public Nullable<int> ReceitaID { get; set; }
        public Nullable<int> IngredienteID { get; set; }
        public Nullable<int> qtdGramas { get; set; }
    
        public virtual Ingrediente Ingrediente { get; set; }
        public virtual UsuarioReceita UsuarioReceita { get; set; }
    }
}
