//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPCookBook.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SPCookbookEntities : DbContext
    {
        public SPCookbookEntities()
            : base("name=SPCookbookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ingrediente> Ingrediente { get; set; }
        public virtual DbSet<IngredientesReceita> IngredientesReceita { get; set; }
        public virtual DbSet<NotaReceita> NotaReceita { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<ProcedimentoReceitas> ProcedimentoReceitas { get; set; }
        public virtual DbSet<ReceitaFavorira> ReceitaFavorira { get; set; }
        public virtual DbSet<TipoReceita> TipoReceita { get; set; }
        public virtual DbSet<TiposItem> TiposItem { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioReceita> UsuarioReceita { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
