//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPCookBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        public int idPerfil { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idIngrediente { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual Ingrediente Ingrediente { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
