//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPCookBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioReceita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuarioReceita()
        {
            this.IngredientesReceita = new HashSet<IngredientesReceita>();
            this.NotaReceita = new HashSet<NotaReceita>();
            this.ProcedimentoReceitas = new HashSet<ProcedimentoReceitas>();
            this.ReceitaFavorira = new HashSet<ReceitaFavorira>();
        }
    
        public int id { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public string NomeReceita { get; set; }
        public Nullable<int> TipoReceitaID { get; set; }
        public Nullable<int> TempoMinutos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientesReceita> IngredientesReceita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotaReceita> NotaReceita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcedimentoReceitas> ProcedimentoReceitas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceitaFavorira> ReceitaFavorira { get; set; }
        public virtual TipoReceita TipoReceita { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
